### ISSUE TITLE
Support for Monoid unification

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#122]
We need to be able to do associative unification with a unit in order to handle explicitly required structural rules in sequent calculi, and (as it turns out) in order to handle semantic tableaux via translation into sequents. 

So this is required, I think, for #57.

**Comment by JakeEhrlich** [comment]
Oh neat, I never thought about a system that required explicit structural rules. Did you have an algorithm in mind?

Also in this context we can assume that monoid unification is only needed at one specific syntatic category right? Like you don't need to unify `f((x * A) * z)` with `f(x * (y * B))` you just need to be able to unify `f(x) * (A * f(z))` with `(f(x) * f(y)) * f(z)` if that makes sense? (here I'm assuming that `f` is an operator in the logic)

If so there might be an easier algorithm than combining E-unification algorithms that would still get the job done. If we further assume matching rather than unification it seems even easier to do efficiently (albeit not in the spirit of whats been done so far). I was taking a stab at describing one as I was writing this but decided I'd sleep on it and simplify later (it was getting a bit hairy)

**Comment by gleachkr** [comment]
You're right that only matching is needed (although unification would be nice!) and only in one syntactic category.

But, AU unification appears to surprisingly nasty. The minimal set of unifiers for a problem can be infinite. The standard example is X*A = A*X. Sending X to any number of copies of A solves the problem, so there's an infinite set of solutions. And they're all minimal: you can't leave in variables, since if you leave any variables in X there will be a different number of A's to the right of the rightmost variable on the two sides of the equation. Plotkin 1972 shows how to find the unifiers, if they exist, but it doesn't terminate when there aren't any unifiers. Schmidt 1998 apparently has a decision procedure.

Anyway, that suggests that finding the full minimal set would be hard. So maybe matching is the way to go. In that case, maybe it would work to 1. convert the two sides of an equation to lists `l1,l2`, 2. nondeterministically compute with state, accumulating a substitution. Maybe kinda:

if `l1` is empty, and `l2` has a variable head, then assign that variable to a unit, and continue with l1 and the tail of l2 (applying the new substitution to the tail of `l2`.

if `l1` is empty, and `l2` has a nonvariable head, terminate this branch of the computation

if `l1` is nonempty, and `l2` is empty, terminate this branch of the computation

if `l1` is `A:l3` and `l2` is `X:l4`, for a variable `X`, then split: on one branch add `X↦ A*Y` to the substitution, where `Y` is fresh, and continue with `l3, Y:l4`, and on another add `X↦unit` and continue with `l1,l4`. In each case apply the new substitution to l4.

if `l1` is `A:l3` and `l2` is `B:l4`, for a nonvariable `B`, then terminate the branch if A!=B, and otherwise continue with l3,l4

What do you think? Seems sort of easy, so maybe matching for AU is easy even if unification is hard?

**Comment by rzach** [comment]
Just out of interest: are the two sides of a sequent represented as terms (rather than lists)? Naively, it seems to me like custom-coding each check (for exchange) on the basis of converting to lists would be easier & more efficient than a general matching algorithm, no? And exchange is the only structural rule where this is relevant, isn't it?
FWIW I think it would be extremely frustrating to make students prove something with the standard exchange rule. So I would be happy to make the exchange rule accept any permutation of the sequence as far as the fix to #57 is concerned.

**Comment by gleachkr** [comment]
Yep! the two sides are represented as terms rather than lists, so dealing with associativity of commas requires a little care. The sequent calculus over a given language is just another language, internally.

I agree that requiring explicit exchanges might not be great for student morale :) Probably best to pack all permutation into a single rule. I think I agree that at least in the case of exchange it would be best to do this as a custom restriction, rather than implementing another matching algorithm.

So, what I'm thinking would make sense would be something like this: implement associative matching, but make it possible, for each rule, to select which form of matching you're using for your Γ,Δ variables in a given sequent: either carnap needs to find a substitution that makes the rule scheme match the user input when both are viewed as sets (this is what happens now), or when both are viewed as lists (this would be AU matching). For something like the "free permutation" rule, you'd have the equivalent of the current "rep" rule (which is just "Γ⊢Δ ∴ Γ⊢Δ", with matching as sets) and you'd add a special restriction to it that the corresponding sides of the seqeunts that the user inputs need to be the same as multisets.

So, you'd have two options, but you'd get some intermediate things (like permutation) as ad-hoc restrictions of the more liberal option. Does that make sense?

**Comment by JakeEhrlich** [comment]
@gleachkr That proposed algorithm is exponential which I think is fine under the circumstances. It also seems correct to me even after taking a bit more than a glance. Specifically I think correctness here just means that it finds a complete set of unifiers for the matching problem (I won't at this time assert they are minimal however). I had hoped that because we only needed it at a single syntatic category that it might be easier to perform unification but that counter example for infinite minimal unifiers kind throws that all out I suppose. That would explain why I wasn't able to make anything nice quite as quickly as I had hoped.

The kind of unfortunate thing is that that algorithm is exponential not in the schematic side but in the concrete side. I feel like a proof where say 30 assumptions accumulate in a sequent is quite plausible That would mean 2^30 steps would have to be run which I'd guess would take a couple minutes and eat a ton of memory depending on how the non-determinism monad was written (depth first would use almost no memory, breadth first would use an exponential amount I think).

Consider `[a, b, c] = [A, Gamma]`, the above algorithm would efficiently break the problem down to `[b, c] = [Gamma]` but would then split into 4 branches from there even though the problem can be solved with a single most general unifier (namely `{A -> a, Gamma -> [b, c]}`). This also seems like the common case so perhaps just adding a case for when the right side is a singleton list would save a lot of time? If `[b, c]` was a much longer list this would have major savings. This doesn't help at all with implementing the exchange rule. That's going to be nightmare fuel for performance on large proofs.

@rzach I belive the problem is challenging regardless of representation. Converting to lists doesn't make it much easier if at all. That said I 100% agree that applying O(n) exchanges to get all of the reorders that you'd need for any given permutation in general would be a nightmare for students and it wouldn't really help with understanding. Unfortunately I'm not sure I see a way to implement that kind of things as a generic rule with any kind of unification. Perhaps there were some unexpected limitations to relying on unification as Carnap does :/

The best I can think of is to have two wrapper types (think sum/product monoids for numbers) that allow switching between communicative monoid unification and pure monoid unification (or matching as that seems possible to solve and monoid unification seems hard).

**Comment by JakeEhrlich** [comment]
Ah seeing Grahams proposal I see that my idea of switching between monoid types was also Grahams idea as well. We still need monoid matching to do that.

**Comment by gleachkr** [comment]
Thanks Jake! Those are great suggestions. `ListT` is depth first (I think `LogicT` is breadth-first) so I'll use `ListT`.

I will try to figure out if somebody knows the complexity of this kind of matching. Maybe it's possible to do better than exponential? I'd like to know the answer, even if worst-case-exponential is OK in this application.

**Comment by JakeEhrlich** [comment]
Another optimization to the matching algorithm: Each variable accounts for some possibly empty range of concrete terms. Variables at the start and end of their range have the start/end of the range fixed as well. Take exchange where you have `[Gamma1, A, Gamma2, B, Gamma3]` for instance. Gamma1 covers a range of `[0, a]`, Gamma2 covers a range of `[b, c]` and Gamma3 covers a range from `[d, n]` with `a < b <= c < d`. There are only O(n^4) such combinations of numbers and 30^4 is *way* less than 2^30. This isn't so hard to implement using non-determinism I believe.
