### ISSUE TITLE
.hs file for Allen & Hand's textbook

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap#136]
This is a slightly modified set of rules from Allen and Hand's Logic Primer. (As an aside, I think that Allen and Hand is a great text for teaching a small class in a classroom---or a large class with TAs. It's not really usable for an online course, though. Plus, although it used to have a nice proof checker, that website seems to be down, and, in any case, that website was nothing like Carnap. All that is to say that there might be other instructors who have used Allen and Hand and now want to try Carnap, and this would make using Carnap, perhaps, more attractive.)

Allen and Hand use the Lemmon-style for proofs, and this file is for Fitch-style proofs. 

Allen and Hand allow both A v B, ~B |- A and A v ~B, B |- A. In this file (and following .ForallxSL), only the former is allowed, although the double-negation rule (DN) is included to cover the latter scenario.

Allen and Hand's biconditional introduction rule is A -> B, B -> A |- A <-> B. I wasn't sure if the "conditionalToBiconditional" rule would work with Fitch, and so I included it along with (A -> B) & (B -> A) |- A <-> B. (And I also wasn't sure if that rule was "biconditionalExchange !! 0" or "biconditionalExchange !! 1", and so I included both.) Ultimately, just one biconditional introduciton rule is needed, though.

And finally, Allen and Hand use RAA for both ~I and ~E (as they are defined in .ForallxSL). I've left ~I and ~E and added an RAA rule. (I'm assuming that having ~I/~E and RAA wouldn't create any confusion for students if they are given only one or the other, and I'm kind of commited to ~I/~E at this point.)

That's the idea anyway. I put this together by inspecting the MagnusSL.hs file and making changes, but I don't really know anything about Haskell.

Hmm, I couldn't attach it with the .hs extension, but anyway, here it is.
[AllenHandFitchSL.txt](https://github.com/gleachkr/Carnap/files/4933265/AllenHandFitchSL.txt)

To get to the issue, the file still needs at least a little tweaking (for <->I, at least, and possibly some other fixing). Can it be added to Carnap at some point?

**Comment by gleachkr** [comment]
Thanks! I've touched this up, and it's now nearly compiling. The `allenOpts` still need to be defined---this is basically a parameter that configures the propositional language parser. So, if it's OK to have the formulas be parsed in the same way as in magnus' Forallx, then we could just use `magnusOpts`.

`conditionalToBiconditonal` ought to be fine for a Fitch system. The biconditional exchange rules let you replace A→B∧B→A with A↔B even if the former occurs under some other connectives rather than at the top level. Do you still want to include that?

Also, would you rather keep it as Fitch-style, or switch to Lemmon-style?

**Comment by loighic** [comment]
Ok, great. Thanks.

Yes, magnusOpts will be fine, I think.

As long as the conditionalToBiconditional rule works with Fitch, the biconditional exchange rules should be taken out. (I probably should have just taken them out myself and hoped for the best with the 'P -> Q, Q -> P |- P <-> Q' rule.)

Keep it as Fitch-style notation please. I'm committed to that at this point.

**Comment by gleachkr** [comment]
These are now available as `.AllenSL` and `.AllenSLPlus`. If you'd like to try them out and see if they're working as you wanted, I can then go ahead and make any final tweaks. I'll also add them to the lists of systems in the documentation.

**Comment by loighic** [comment]
Awesome. Thank you!

I'm testing it out now. It looks like there might be a couple of things. I'll let you know.

**Comment by loighic** [comment]
Looks good. There are just a few things.

(1) The double negation rule (DN) works in .AllenSLPlus, but it should also be in .AllenSL. 

(When it is used in .AllenSL, the error is "Error on line ... . Can't match these premises with this conclusion, using this rule." Although DN is listed with the "Expecting AS, PR, &I, . . . etc." in .AllenSL.)

(2) Modus tollens (MT) isn't working in either .AllenSLPlus or .ForallxSLPlus. The error is "Can't read line ... . There may be a typo."

~~~{.Playground .AllenSLPlus options="fonts tabindent render" guides="fitch"}
P -> Q    :PR
~Q    :PR
~P    :MT 1,2
~~~

(3) And finally RAA isn't working. My intention was that RAA would work just like ~E and  ~I (as they are defined in .ForallxSL). That is, anytime that ~E and ~I are used, they could be replaced by RAA. (And ~E and ~I work fine in .AllenSL.) 

The error when using RAA (in .AllenSL) is "Dependencies are of the wrong number or form." For instance, with this:

~~~{.Playground .AllenSL options="fonts tabindent render" guides="fitch"}
P v Q    :PR
~P -> ~Q    :PR
    ~P    :AS
    ~Q    :->E 2,3
    Q    :vE 1,3
P    :RAA 3-5 
~~~

That said, I don't actually need RAA. I'll continue to use ~I and ~E. But I thought that RAA would be nice (and relatively easy) to include for others who might be using or have used Allen and Hand. Looking over the file that I created, however, I can see that maybe I didn't define RAA correctly, or at least not the simplest way. So, if it only takes a tweak, then we might as well include it. But if it's going to take more than that, then maybe RAA should just be deleted.

**Comment by gleachkr** [comment]
Thanks for the careful testing! I think I've addressed these. You can see the changes here: 02c2e05e8504a7d6b29502d87bf9fe8dd9824499.

(1) was caused by the fact that MagnusSL was configured to use only first-order unification. This is slightly faster (not perceptible in practice, in my experience), but it can't handle rules in which a nested expression is replaced, hence the trouble with DN. So this is the change around line 204.

(2) was caused by a typo in MagnusSLPlus that got carried over---basically, the parser wasn't catching the "MT" when it was detected. Changes for this one are at line 292.

(3) was caused by the ordering of "RAA" vs "R". The parser, as configured, accepts a string even if there's some trailing stuff, so it was reading "RAA" as `R`. Having it check for "RAA" before checking for "R" fixes this. Changes for this are at line 156.

**Comment by loighic** [comment]
Oh, interesting. Glad they were all relatively simple.

Looks like everything works. Thank you! This is great.
