### ISSUE TITLE
Lots of missing student points/data?

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#165]
Suddenly, most of my students have 0 points? Not sure what happened. Hoping that their scores are recoverable!

**Comment by dsanson** [comment]
Huh. Now their scores seem to be back. That is good!

**Comment by dsanson** [comment]
My students also report that their scores were zero this morning, but have now returned.

**Comment by gleachkr** [comment]
Yep. This was the result of some updates that I then rolled back, after seeing what happened. The trouble is that yesod changed how it represented database keys, so that when Carnap looked for keys in the new representation, they weren't present.

I originally thought that this was the intended behavior for yesod, but @lf- has now figured out that this is a result of https://github.com/yesodweb/persistent/issues/1104. So rather than moving the DB to the alternate representation, we're going to switch the dependencies to incorprate yesod's fix for the regression.
