### ISSUE TITLE
Sorting of problem sets

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#203]
In the student view, if you sort by problem set, the sort order is weird: CP3 sorts before CP2.1

**Comment by gleachkr** [comment]
Hm, right.

It looks like the ordering is, for period-free strings, by length and then within a fixed length lexically on the order of characters (so that CP2 comes before CP10). The overall ordering is gotten by splitting at periods and then ordering the lists of chunks by length, and then lexically on the period-free ordering.

Probably, though, the overall ordering should just be lexical on the period-free ordering, so that if S > T then S.WHATEVER > T.

**Comment by gleachkr** [comment]
Should be closed by 9d8eda46e8d1b94e7a38ee0c848519d943f0624a
