### ISSUE TITLE
Incorrect rule accepted

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#205]
A student reported this:

On https://carnap.io/shared/rzach@ucalgary.ca/279%20Problem%20Set%2010%20F20.md problem 10.5, Carnap accepts the following proof fragment:
```
    ~∃x(P(x) → ∀xP(x)) :AS
        P(a) :AS
            ~AxP(x) :AS
                ~P(a) :AS
                    P(a) :AS
                    _|_:~E 4,5
                    Ax P(x) :X 6
                P(a) -> Ax P(x) :->I5-7
                Ex(P(x) -> Ax P(x)):EI 8
                _|_ :~E 1,9
            P(a) :IP 4-10
            Ax P(x) :AI 11
```
But the last line should trigger a "a not fresh" error since it occurs in the open assumption on line 2.

The hints on mouseover on the `+` signs on the right only show the formulas on the left of the turnstile that the justified formula depends on (and none actually use line 2). So it's a sound inference but it's confusing that Carnap accepts it.

**Comment by gleachkr** [comment]
I think this is the expected behavior, but you're right, it's confusing and should be changed. The reason this is happening is that the calgary system currently uses a system-agnostic fresh-variable check that only takes place after the proof is translated into a tree of sequents (there a footnote about it here: https://carnap.io/srv/doc/montague.md#fn1), so it can't see this kind of "harmless" staleness. It won't allow anything that shouldn't be provable to be proved, but it's not ideal for students.

**Comment by gleachkr** [comment]
OK, I've added some structural constraints to AI and EE that flag non-fresh variables, (either ahead of the AI inference, or ahead of the EE assumption) even if they aren't used.

**Comment by rzach** [comment]
Thanks so much!
