### ISSUE TITLE
Partial proof detected as correct.

### ISSUE THREAD

**Issue by Andrew-Miner** [Carnap/Carnap#212]
![332c9fe2092a3b28ee4db3a23376ae37](https://user-images.githubusercontent.com/26013579/102031486-06371400-3d6b-11eb-8eb7-c2f659dbe4d2.png)
This happened while I was completing a homework assignment. I'm not familiar with Carnap beyond using it as a student, so perhaps this could be a user error made by my professor?

**Comment by gleachkr** [comment]
Thanks for the bug report. This one is on me I'm afraid. Carnap only understands variable bindings up to what's called [α-equivalence](https://en.wikipedia.org/wiki/Lambda_calculus#Alpha_equivalence), so although in standard natural deduction settings the proof ∃x∃yL(x,y) ⊢ ∃y∃xL(y,x) is substantial, Carnap jumps the gun and regards the initial premise as establishing the conclusion right away, since it can't see the difference between the two. I'll need to make this more explicit in the documentation.
