### ISSUE TITLE
Permissive discharge

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#22]
It looks like in the Gentzen NJ proof checker it is required to enter a discharge label for every application of ->I. But discharge should be permissive, ie, it should be allowed to not discharge anything. Otherwise you can't prove A -> (B -> A).

**Comment by rzach** [comment]
Also, if you remove the discharge label (n) from an ->I, every rule label will gray out and the mouseover hint says "waiting for parsing to be completed".

If the assumption doesn't match the antecedent of the conditional, the mouseover hint on all subsequent inferences will be "assumption mismatch" (even if the subsequent inferences are correct)

**Comment by gleachkr** [comment]
At the moment, you can only prove something like A->(B->A) by citing an assumption that you don't actually use for the discharge. That's not intuitive. I'll change it, but will leave it as permissible to cite vacuous assumptions that don't actually occur. (I think this fits with the conventions of *Sets, Logic, Computation*, is that correct?)

The other two bits of behavior (A. not accepting inferences downstream from an error, and B. not checking any part of a proof if any other part fails to parse) might deserve their own issues. I think the second is fixable, but the first is tricky since on the current design checking an inference means computing a sequent proved, and knowing what's proved downstream requires knowing what's proved upstream. Maybe it'd be enough to have a more illuminating error message?

**Comment by rzach** [comment]
I had never actually thought of the possibility of a rule using a discharge label that doesn't occur, but yes, that is allowed in OLP. It doesn't hurt anything and it would make things harder to require that every discharge label used on a rule actually labels an assumption. But from the point of view of users, it may make sense to show an error if that happens. I can imagine students being incredibly frustrated if their entire proof checks but doesn't turn green because they've mislabelled an inference.

I'll make two new issues for the other two.

**Comment by gleachkr** [comment]
Should be fixed by 3ef6d3fd384bfc950f4c85f3965b4ca8d272b2c0
