### ISSUE TITLE
Allow course textbook to not be assigned

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#229]
When I try to assign a Carnap page as the "textbook" for a course, the only options are pages that are assigned in the course.  This may be confusing; I'd prefer it if the "Upcoming assignments" section in the Student User Page only showed actual assignments.  (I could assign that page and make it hidden, but then I have to put in a password.)
So: can we allow *any* uploaded document as the textbook page?

**Comment by rzach** [comment]
Actually I'm wondering if it shouldn't be possible to assign *any* shared file as the textbook, not just my own? Otherwise I have to dowload & upload my own copy of say the Carnap book in order to be able to set it as the course textbook?

**Comment by gleachkr** [comment]
What about displaying the textbook separately from the other assignments? So students would have a link to it on their user page, but also the list of assignments that come from within the textbook?

For the second idea - maybe a good mechanism for something like this would be to add an "adopt" button in addition to the download button in the shared document listing, so that people can quickly adopt class materials that other people have developed? This would probably also motivate some work to make the shared document listing a little more user-friendly and navigable.

**Comment by rzach** [comment]
Yes to the first.

Second: that would be cool. But what if the original author/uploader deletes or changes the file?  Maybe: ability to copy a shared document? (But then we get into copyright issues I think, unless we require that every shared document is uploaded as CC BY or something?)

**Comment by gleachkr** [comment]
Maybe we could add a new sharing scope: CC BY, to enable the copy button?

**Comment by rzach** [comment]
That might be an idea.  One issue with CC BY is credit.  It sortof hard to put credit on course materials; if they are displayed on the page itself it'll look odd since you're showing things to your students that say someone else made them.  But we could have a metadata entry for the license and credit info which is automatically populated when you upload with that sharing scope (unless it is present). Perhaps we can have some options (CC BY, CC BY SA, CC0)?
Perhaps this is making things too complicated/bloated.  I see you already stopped the textbook from being displayed. I think that's good enough for now. So unless you want to keep it open, this is ok to close as far as I'm concerned.

**Comment by gleachkr** [comment]
OK - let's add a separate issue for copying textbooks when the time comes. Might be best to include CC status as pandoc metadata (along authorship) and render it appropriately using a `<meta>` tag? Anyway, I'll think about that.
