### ISSUE TITLE
max-width only set on <p>

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#235]
The CSS for Carnap pages has `<p>` style set to `max-width: 650pt;` but not on any other  elements. So eg `<ul>` and `<ol>` elements get to be much wider than body text.

**Comment by rzach** [comment]
Perhaps set it on `<body>` or `<article>` instead so it inherits? But maybe we want the problem `<div>`s to be as wide as the viewport allows?

**Comment by gleachkr** [comment]
Yeah, I think the more local change is preferable. Should be fixed with  f9b3a467a6072f87fcfccf236ed565912704646c, deploying now.

**Comment by rzach** [comment]
Note that since the nav menu is a `<ul>` the menu is now further left, not sure if that was desired/intended.

**Comment by gleachkr** [comment]
Unintended, thanks for noticing.

**Comment by rzach** [comment]
While you're there maybe also set it on `<h1>` etc? And possibly `<blockquote>` and `<dl>`

**Comment by lf-** [comment]
I did some similar CSS hacking at the top of https://github.com/Carnap/Carnap-Documentation/blob/master/doc/api.md to make it work properly on mobile

**Comment by gleachkr** [comment]
Done, for `blockquote` and `dl`. I am conflicted about `h1` etc. Because those are larger, they don't lose a whole lot of legibility, even if they're wide, and it might be preferable to have a header that's wider than your text rather than a linewrap in your header (tufte css allows wide headers, for example). On the other hand, uniformity... Here are images of the options:

![20210224_09h42m35s_grim](https://user-images.githubusercontent.com/6383381/109027714-b340dd80-7686-11eb-941d-4347466549b1.png)
![20210224_09h42m04s_grim](https://user-images.githubusercontent.com/6383381/109027717-b3d97400-7686-11eb-8e67-a19e427fec18.png)

What do you all think?

**Comment by lf-** [comment]
We should check for horizontal overflow on mobile view, as I know I've hit a bunch of it, in particular with images and to a degree code also. It would be preferable if overlong code blocks overflowed themselves horizontally instead of the `<article>`.


It's possible that h1s are also part of the group of elements causing horizontal scrolling.

**Comment by gleachkr** [comment]
Just checked - the `h1`s reflow properly when there's a narrow viewport. There is a definitely a more global issue with making sure that the standard styles don't introduce annoying horizontal scrolling when there's a narrow viewport. Fixing this might also require tweaking some of the exercise css.

**Comment by rzach** [comment]
I have no preference.

**Comment by gleachkr** [comment]
OK, I think this is OK to close then. We can maybe open a seperate issue for the horizontal scrolling on mobile.
