### ISSUE TITLE
REST API for instructor actions

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#246]
The  new API access is wonderful!

Any chance of extending the API to include access to student submission data as well? It would be convenient to grab the exported CSV from the CLI. I've already replaced my excel spreadsheet with a python script, which applies my retake policy, and spits out a CSV ready for import to my CMS.

This would also allow me to automate and improve some of the things I am now doing to offer students retakes. A script could poll Carnap for submission data, construct individualized "retake" assignments on the fly from a question bank (or partial "retake" assignments, just asking students to redo the problems they got wrong), upload those assignments to Carnap, and send the link and access code to the student. 

Right now, I have a Discord server for the class, and students ask for retakes by sending me a DM on Discord. And I have, for each retake-able assignment, several alternate version uploaded. I've been thinking about handing this task over to a bot written in python. But I'd like the bot to enforce a waiting period between retakes, and a "meet with the instructor after n retakes" requirement. This would be possible if the bot could check submission times on Carnap....

**Comment by gleachkr** [comment]
These are great ideas! I hadn't even thought about the chat-bot use case, but that's a perfect application. So what endpoints do we need here?

1. Assignment upload
2. Student submission data - what's needed here, and how should it be presented? Something like an endpoint for each student, in each of your classes, which provides a list of all the student's submissions? might want to be a little cautious with polling too rapidly here, but I think the current rate limit (one request per second or so) would be fine.
3. CSV download of the whole grade spreadsheet

Anything else?

**Comment by dsanson** [comment]
For (2): I'm not sure what the relevant costs are for different things. A list of all of a student's submissions with scores and timestamps would be great. Restricting it to a single assignment would be helpful, especially if that reduces the hit to the server. Of course, if that *increases* the hit to the server, it is easy enough to filter the data on the other end.

**Comment by gleachkr** [comment]
I think both ought to be fine - each individual row in the grade table of the instructor page costs about as much (a little less than) a full list of a given student's submissions, so it's not too bad, as long as it's one at a time and not 300 at once.

I think we can probably do both endpoints. So, for students something like:

- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/submissions
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/extensions
- [x] POST https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/extensions
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/accomodations
- [x] PATCH https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/accomodations
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/students/:studentId/assignmentTokens
- [x] DELETE https://carnap.io/api/v1/instructor/:instructorIdent/courses/:courseTitle/students/:studentId/assignmentTokens/:tokenId

(assignment tokens record the start-time for a student accessing a time-limited assignment)

For assignments, something like:

- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments
- [x] POST https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments/:assignmentId
- [x] PATCH https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments/:assignmentId
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments/:assignmentId/submissions
- [x] GET https://carnap.io/api/v1/instructors/:instructorIdent/courses/:courseTitle/assignments/:assignmentId/submissions/:studentId

And maybe do grade calculations on the client-side, so that you can throttle (like the instructor page does) the requests necessary to get all the submissions for every student.

**Comment by lf-** [comment]
I am not entirely familiar with the use case but I note that the pluralization of the path components is inconsistent in this proposal.

**Comment by gleachkr** [comment]
Shoot, thanks. Fixed.

**Comment by gleachkr** [comment]
Remaining:

- [x] making assignment PATCH accept human-writable dates
- [x] documentation

**Comment by gleachkr** [comment]
Documentation is in an acceptable state - can continue to polish, but I think this is done.
