### ISSUE TITLE
OLPExArith parser issue

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#251]
https://carnap.io/shared/rzach@ucalgary.ca/olptest.md first exercise:
`Az((z < m \/ m < z) -> [(Se(m,n) -> Se(m,n')) /\ (S_(m,n) -> S_(m,n')) /\(SI(m,n) -> SI(m,n'))])`
gives a parser error
`(line 1, column 7): unexpected "<" expecting space or ")"`
But I think it's the `[]` that creates the problem -- it goes away if I change the `[]` to `()`.

**Comment by gleachkr** [comment]
Yep, these parsers just use ordinary parentheses. I'll add square brackets tomorrow.

**Comment by rzach** [comment]
While you're at it: would it be very easy to allow non-alphanumeric symbols in the predicate symbol strings for the `openLogicEx*` languages? I'd like to write things like `P_>` or `P#`.  I imagine there are conflicts with some symbols like `<`.  Not a big deal if not, I can just use `Pstart` and `Phash` or whatever.

**Comment by gleachkr** [comment]
Shouldn't be a problem, I think. Any particular set of symbols?

**Comment by gleachkr** [comment]
OK, Square brackets added, with cdd00361270f6631d208a5d3c277953d9e0f83b0

**Comment by rzach** [comment]
Right now I'd just need `>` and `#`.

**Comment by gleachkr** [comment]
OK, added, to all the "Ex" systems. I've introduced a "extra symbols" parameter, so the extra symbols allowable can now be set per-system, and tweaked pretty easily.

**Comment by rzach** [comment]
Amazing thank you!

**Comment by rzach** [comment]
Oh just to confirm something: This would cause problems if these languages allow propositional constants since `P > Q` would then maybe not parse. But they all don't right? (I don't think they need to; I'll just mention it in the docs)

**Comment by rzach** [comment]
In general would there be a problem allowing symbols that are also used as keyboard equivalents such as `@`?  I assume not since it deals with `3` just fine. Then maybe we can just allow any symbol other than `(`? 

Actually, constants also get this treatment. So `c<d` would be a potential problem but if the parser can tell that here `<` is less than then.  If there is a problem, then let's keep it as is. If not, maybe the parser can simply allow all symbols rather than a given list.

**Comment by gleachkr** [comment]
> Then maybe we can just allow any symbol other than `(`?

At first I thought, "yes!", but then writing it out, I began to worry that there might be some problems with infix function symbols. Like, if I have a string function expression like `a+b`, then the parser might fail given a sentence like `F(a+b(c))`, since it could see the string part `a+b` as a complete term, take itself to have found the term it's been expecting, move on to expecting, e.g., a comma or `)`, and then bail out when it encounters `(`.

The `a<b` example would be OK, I think, since the parser wouldn't be able to parse this as a string term, and would then backtrack to trying to parse `a` as a constant. But something similar could happen with a sentence like `a<(b+c)`, which could also be *successfully* parsed as a term, causing the parser to expect an infix predicate symbol afterwards.

These  wouldn't *necessarily* be a problem, if the parser was really smart about the order in which it tried out different options, or if more complicated backtracking logic was put into place. But it could get kind of fragile.

**Comment by rzach** [comment]
Yes that's what I was worried about too.  I don't really have a use case yet although I think if you're representing primitive recursive functions in arithmetic something like `A_+(x,y,z)` might be useful. But then `Add(x,y,z)` is just as good and just as short.
