### ISSUE TITLE
Parser issues

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#278]
The last examples in 
https://carnap.io/srv/doc/systems.md#hardegree-symbolic-logic
and
https://carnap.io/srv/doc/systems.md#open-logic-project
don't parse.
(In Hardegree, the smash product/contradiction symbol doesn't show on my browser, but maybe that's just me)

**Comment by gleachkr** [comment]
Hm. I think the HardegreePL system doesn't include identity (maybe it should? I don't think it does in the modal logic book, but Hardegree seems to change the details in different presentations), which seems to be what the parser is rejecting. The error message isn't great, but basically it's providing a report of what went wrong with the parser's first theory of the sentence's syntax---something like "here's an `Ax`, perhaps this is an atomic sentence? No, can't be, I'm now encountering a `(`"---rather than what went wrong with the theory that we're interested in.

In the second case, I think there's an extra `)` at the end of the sentence being parsed. This might point towards a problem with the subset notation `<(`, though - if your text editor tries to do anything clever to help balance parentheses, then this is going to cause problems. Perhaps that should be tweaked.

**Comment by gleachkr** [comment]
The smash product issue kind of suggests that the smash product should be in Fira Logic - I think the browser currently needs to fall back on system fonts to provide it.

**Comment by rzach** [comment]
I fixed the parser issues -- you were right about both.
The smash product thing is weird. I could have sworn that this used to display fine.

**Comment by rzach** [comment]
(Got it -- had upgraded Ubuntu, lost the Noto Math fonts that have it.)
