### ISSUE TITLE
Type-checking seems to become undecidable, when ghc > 7.10.3 used

### ISSUE THREAD

**Issue by phlummox** [Carnap/Carnap#4]
Hi! Not necessarily a bug, but while experimenting with just the `Carnap/` package, I noticed that although it seems possible to compile with older versions of ghc (e.g. 7.10.2, and stackage lts-3.22) than you used, on any newer version of ghc I have access to (8.0.1 and higher, and stack lts-7.0 or higher), type-checking seems to become undecidable. (Or at least, I assume that's what's happening; the compiler never finishes, and eventually sucks up all available memory on my machine ...)

I'm intending to investigate, and see if I can find out what changed between 7.10.3 and 8.0.1 that causes the difference - I wondered if you had noticed this yourselves, or might have any suggestions on what modules might be contributing to the problem?

**Comment by gleachkr** [comment]
Huh, interesting. I haven't run into this myself, but it's been a while since I experimented with building using a more recent compiler. Moving to a more recent lts is a target, though. I should have some time during the coming week to poke around. I can only wildly speculate about the cause at this point. Nothing in here: https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/8.0.1-notes.html leaps out at me, though maybe I should look somewhere else. If you figure anything out, definitely please let me know.

**Comment by phlummox** [comment]
My initial guess was that some ghc extension might have changed its semantics between 7.10 and 8.0, but likewise, nothing has leapt out at me yet. No worries, I'll keep you posted :)

**Comment by phlummox** [comment]
Okay, an update, but unfortunately not very informative, I'm afraid. At revision 22cc589316f12e94a32dd9964963d64999228346 and earlier, GHC 8.0.1 and later versions can be coaxed into compiling `Carnap/` by (a) adding a couple of type signatures, and (b) commenting out parts of [Carnap.Core.Examples.ToyLanguages](https://raw.githubusercontent.com/gleachkr/Carnap/22cc589316f12e94a32dd9964963d64999228346/Carnap/src/Carnap/Core/Examples/ToyLanguages.hs) that they apparently can't handle. \
(Relevant patch attached, [22cc5893.txt](https://github.com/gleachkr/Carnap/files/2280746/22cc5893.txt).)

After that point (from 0a1d45b1c88eec220c391f63236d8db0596e3a8b, onwards), no matter what I do, the "Renamer/typechecker" phases of compilation for `Carnap.Calculi.NaturalDeduction.Parser` and `Carnap.Calculi.NaturalDeduction.Syntax` reliably cause GHC to use >= 125MB heap memory (compared to <20MB, for most modules in the package),  and in fact one or the other of them seems (as far as I can tell) to consume heap space without bound.

I'm interested in experimenting with the ideas in https://arxiv.org/abs/1803.03092 with more recent versions of GHC, and don't have sufficient familiarity with GHC to diagnose the problem in more detail than I have, so I'll try implementing things from scratch, using GHC >= 8.0.1, and see if/where I run into issues.

Thanks again for your help!

**Comment by gleachkr** [comment]
Thanks for all the information. This gives me a good idea of where to start. I'll start an ghc-8 branch and see if I can make any progress there. In the mean time, if your project will be GPL, please feel free to help yourself to Carnap.Core. It sounds like that part might play nice with 8.0. The implementation of Huet's algorithm also ought to be portable if you want to use just that.

**Comment by phlummox** [comment]
No worries, and thank you :) At this stage I'm just learning how it works, and implementing things from Swierstra's "Data types a la carte" for comparison. If anything useful comes of it, then yes, I'll open source it.

**Comment by gleachkr** [comment]
OK, I think the problem was the use of something like the [class synonym by undecidable instances trick](https://downloads.haskell.org/~ghc/7.10.3/docs/html/users_guide/type-class-extensions.html#undecidable-instances). This worked in 7.10.3, but seems to make the typechecker loop in the 8.* series. For me, the context-stack limit caught the problem before it ate all my memory. But if I set `-fcontext-stack=0`, I saw the behavior you're describing.

The Carnap package in the new ghc-8 branch compiles for me. Interestingly, with 8.0.1 and 8.0.2 I get one kind of ghc panic, and with 8.4.3 I get another ("the impossible happened", twice in one day...). But 8.2.2 works. The tests are still not quite working right. All seems well in the repl, but some overlapping typeclasses are not being resolved correctly in `stack test Carnap`. I've put in [a question](https://stackoverflow.com/questions/51882493/in-ghc-8-2-2-can-overlapping-instance-resolution-depend-on-whether-a-file-is-in) on stackoverflow about that last bit, to see if I can get some insight on that last bit.

**Comment by treeowl** [comment]
You should certainly file a ticket in the GHC Trac system.

**Comment by phlummox** [comment]
Ah cool. I'll try out the ghc-8 branch - many thanks for that. If I happen to figure out what's going on with the tests, I'll keep you posted.

**Comment by gleachkr** [comment]
Here's something like a minimal example of the problem that the tests have revealed (the one from the stackoverflow question above): [GHC-Repro](https://github.com/gleachkr/GHC-Repro).

To see the problem in action, run `test.sh`. The good news is that this particular (mis?)-behavior seems to be specific to 8.2.2. It doesn't show up in 8.4.3, or in any other version I've tried.

@treeowl: since this doesn't appear to be affecting HEAD, do you think the GHC team would still want a ticket about it?

**Comment by treeowl** [comment]
@gleachkr, yes, please do. Even when the problem is gone, it can be helpful to know *when* it went away. Also, if the problem remains, but no longer shows up under quite the same circumstances, it can be useful to try to gather lots of related examples to investigate. The worst that can happen is that someone who knows something will close it as a duplicate.

**Comment by hSloan** [comment]
@gleachkr Great talking with you today. I'll be reproducing "the impossible happened" error and observing the current build process. Looking forward to working on this project with you.

**Comment by gleachkr** [comment]
GHC Trac ticket for the 8.2.2 issue: https://ghc.haskell.org/trac/ghc/ticket/15599

**Comment by dsanson** [comment]
I am happy to see the ghc-8 branch. The master branch won't build on OS X Sierra or newer, because trying to build yesod exceeds [linker limits introduced by Apple](https://ghc.haskell.org/trac/ghc/ticket/14444). But supposedly this is fixed in more recent versions of ghc. I have successfully built yesod using ghc 8.4.3, so I am hoping that once Carnap is updated to a more recent version of ghc, I will be able to build it too!

When I try `stack build` on the ghc-8 branch, I get a bunch of dependency errors:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for Carnap-Server-0.0.0:
    aeson-1.3.1.1 from stack configuration does not match >=0.6 && <0.12  (latest matching version is 0.11.3.0)
    directory-1.3.1.5 from stack configuration does not match >=1.1 && <1.3  (latest matching version is 1.2.7.1)
    http-conduit-2.3.2 from stack configuration does not match >=2.1 && <2.2  (latest matching version is 2.1.11)
    persistent-2.8.2 from stack configuration does not match >=2.0 && <2.6  (latest matching version is 2.5)
    persistent-postgresql-2.8.2.0 from stack configuration does not match >=2.1.1 && <2.6  (latest matching version
                                  is 2.5)
    wai-logger-2.3.2 from stack configuration does not match >=2.2 && <2.3  (latest matching version is 2.2.7)
    yesod-1.6.0 from stack configuration does not match >=1.4.3 && <1.5  (latest matching version is 1.4.5)
    yesod-auth-1.6.5 from stack configuration does not match >=1.4.0 && <1.5  (latest matching version is 1.4.21)
    yesod-core-1.6.8.1 from stack configuration does not match >=1.4.17 && <1.5  (latest matching version
                       is 1.4.37.3)
    yesod-form-1.6.3 from stack configuration does not match >=1.4.0 && <1.5  (latest matching version is 1.4.16)
    yesod-static-1.6.0.1 from stack configuration does not match >=1.4.0.3 && <1.6  (latest matching version
                         is 1.5.3.1)
needed since Carnap-Server is a build target.

In the dependencies for yesod-markdown-0.11.1:
    blaze-html-0.9.1.1 from stack configuration does not match >=0.5 && <0.9  (latest matching version is 0.8.1.3)
    blaze-markup-0.8.2.2 from stack configuration does not match >=0.5 && <0.8  (latest matching version is 0.7.1.1)
    pandoc-2.2.1 from stack configuration does not match >=1.16 && <1.18  (latest matching version is 1.17.2)
    yesod-core-1.6.8.1 from stack configuration does not match >=1.2 && <1.5  (latest matching version is 1.4.37.3)
    yesod-form-1.6.3 from stack configuration does not match >=1.3 && <1.5  (latest matching version is 1.4.16)
needed due to Carnap-Server-0.0.0 -> yesod-markdown-0.11.1

Some different approaches to resolving this:

  * Set 'allow-newer: true' in /Users/desanso/.stack/config.yaml to ignore all version constraints and build anyway.

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build
    configuration. This can be convenient when dealing with many complicated constraint errors, but results may be
    unpredictable.

  * Recommended action: try adding the following to your extra-deps in /Users/desanso/Software/Carnap/stack.yaml:

aeson-0.11.3.0@sha256:81676f93966361e4d1b9331498c5b6ddd884669786226eb9016a19608482fa69
blaze-html-0.8.1.3@sha256:ad02bdfc85199ea1d2597a8d0f345df9a9ec048ceda19e02a822b860b9567770
blaze-markup-0.7.1.1@sha256:b37c8c620c6d21a6b9b0efd8fbaf5753d32bcb470f2d2c27752c7d60413eaf25
directory-1.2.7.1@sha256:461a51126f2d0ccca4036ab75808bdd3938636b9d37d41601107f7b58e04bade
http-conduit-2.1.11@sha256:de112a512afc2b84106e047316e5bfd88de0dadd3657eeab17ad1e793f213dc5
pandoc-1.17.2@sha256:20ffdceba32263927bb9cbe7ae2376a8d2bf482e21797e9fab1705cae2845b53
persistent-2.5@sha256:a6c328c1d19f870e684beaa7c7de592244f60546240ade954a68209d6d4a44eb
persistent-postgresql-2.5@sha256:fb8c7c80f2e38665aa03ba79b826d6d74771b3a1800ea906003c81ebf93526f8
wai-logger-2.2.7@sha256:c9efc74e110d38778aeb16b8cc8a105eb6044162af8cc984b0c04f3f232dda83
yesod-1.4.5@sha256:a8334d823523e2d5c088d5642b21800dbca41aef65dad6588ec29d757c5bf1f3
yesod-auth-1.4.21@sha256:d33aace1b8ca76858c569551ab158b531cb616f528b09247136886fff40e479d
yesod-core-1.4.37.3@sha256:574bcc8079527a5caae88a76f877b09bae7b4bce96ee3537955aff3122baf941
yesod-form-1.4.16@sha256:06b59bcf7a30a9bf9e913d4885bd33ac93da0a670e90e677376efef619d997ba
yesod-static-1.5.3.1@sha256:7865f3038b9741e3fd8cffdf8ea36d7406d22588840ed1346d2156575b084a09

Plan construction failed.
```

So I tried setting `allow-newer: true`, but that gets me the following error:

```
[47 of 69] Compiling Carnap.Calculi.NaturalDeduction.Checker ( src/Carnap/Calculi/NaturalDeduction/Checker.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/Carnap/Calculi/NaturalDeduction/Checker.o )

src/Carnap/Calculi/NaturalDeduction/Checker.hs:92:5: error:
    Not in scope: type constructor or class ‘MaybeStaticVar’
   |
92 |   , MaybeStaticVar (lex (ClassicalSequentOver lex))
   |     ^^^^^^^^^^^^^^

src/Carnap/Calculi/NaturalDeduction/Checker.hs:133:5: error:
    Not in scope: type constructor or class ‘MaybeStaticVar’
    |
133 |   , MaybeStaticVar (lex (ClassicalSequentOver lex))
    |     ^^^^^^^^^^^^^^

src/Carnap/Calculi/NaturalDeduction/Checker.hs:173:5: error:
    Not in scope: type constructor or class ‘MaybeStaticVar’
    |
173 |   , MaybeStaticVar (lex (ClassicalSequentOver lex))
    |     ^^^^^^^^^^^^^^

src/Carnap/Calculi/NaturalDeduction/Checker.hs:213:5: error:
    Not in scope: type constructor or class ‘MaybeStaticVar’
    |
213 |   , MaybeStaticVar (lex (ClassicalSequentOver lex))
    |     ^^^^^^^^^^^^^^

src/Carnap/Calculi/NaturalDeduction/Checker.hs:254:5: error:
    Not in scope: type constructor or class ‘MaybeStaticVar’
    |
254 |   , MaybeStaticVar (lex (ClassicalSequentOver lex))
    |     ^^^^^^^^^^^^^^
```

**Comment by gleachkr** [comment]
Just pushed a bunch of commits to the ghc-8 branch, pulling in updates from master and making some minor tweaks.

I think the first set of errors @dsanson encountered are from the version constraints in the cabal file for Carnap-Server. I'm also using allow-newer to ignore them for now, but eventually I think the version bounds should be just be updated.

On the second set of errors - those required some changes, but... Really good news: the Carnap module seems to be building, and preliminary testing suggests that it's working properly. Carnap-Server is not building yet, roughly because of changes in its imports. But this is, I think, not a hard problem in the same way that the GHC issues earlier in this thread were.

It'll also be some more work to get the GHCJS parts of the program working with a more recent GHC version. I'm hoping that once https://github.com/matchwood/ghcjs-stack-dist/issues/10 is finished, the compiler-wrangling part of this will be easy. But until then, once Carnap-Server is building, it should be possible to just use JS generated by the main branch.

I'll try to put in some more work on this soon! Would also welcome PRs that help get Carnap-Server up to date with lts-12.16.

**Comment by dsanson** [comment]
Yes! Carnap now builds for me (but not Carnap-Server).

**Comment by gleachkr** [comment]
The latest commit on ghc-8 gets Carnap-Server building for me, and behaving OK, although I need to do some more testing.

**Comment by gleachkr** [comment]
OK, testing looks good. It should now be possible to build the server on OSX with ghc-8.4.4 (:crossed_fingers:). This can be done with `yesod-bin`, if that's installed (probably the best way of doing this) using

```
APPROOT='http://localhost:3000' DATAROOT="../dataroot" BOOKROOT="../Carnap-Book/" yesod devel
```

Or without using

```
APPROOT='http://localhost:3000' DATAROOT="../dataroot" BOOKROOT="../Carnap-Book/" stack build --ghc-options -DDEVELOPMENT
```

**Comment by dsanson** [comment]
Testing this out today. Failed on my first attempt. The error messages suggest that the problem is missing ghcjs files. You mentioned above that the old ghcjs files would probably work, and I am guessing it worked for you because you already had those files built. So I'm building Carnap-GHCJS (using ghc-7) to see if that fixes it.

```
Carnap-Server-0.0.0: build (lib)
Preprocessing library for Carnap-Server-0.0.0..
Building library for Carnap-Server-0.0.0..
[16 of 32] Compiling Handler.Rule     ( Handler/Rule.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/Handler/Rule.o )

/Users/desanso/Software/Carnap/Carnap-Server/Handler/Rule.hs:62:33: error:
    Variable not in scope: ghcjs_allactions_lib_js :: Route Static
   |
62 |             addScript $ StaticR ghcjs_allactions_lib_js
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^

/Users/desanso/Software/Carnap/Carnap-Server/Handler/Rule.hs:63:33: error:
    Variable not in scope: ghcjs_allactions_out_js :: Route Static
   |
63 |             addScript $ StaticR ghcjs_allactions_out_js
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^

/Users/desanso/Software/Carnap/Carnap-Server/Handler/Rule.hs:69:33: error:
    Variable not in scope: ghcjs_allactions_runmain_js :: Route Static
   |
69 |             addScript $ StaticR ghcjs_allactions_runmain_js
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building package Carnap-Server-0.0.0 using:
      /Users/desanso/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.2.0.1 build lib:Carnap-Server --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by gleachkr** [comment]
Ah, right. I think you're right - the issue is that the symbolic links under `Carnap-Server/static/ghcjs` are not pointing at anything, since Carnap-GHCJS hasn't been built. 

If you build it, you might still need to renew those links to point at the appropriate files under `Carnap-GHCJS/.stack-work/dist/(this part will depend on your machine)/Cabal-1.24.0.0_ghcjs/build/`.

In case it doesn't build, or takes too long to build (it really can take a while to initially get ghcjs set up), I've attached the files you need here: [ghcjs.tar.gz](https://github.com/gleachkr/Carnap/files/2612759/ghcjs.tar.gz). You should be able to just decompress and replace the ghcjs directory (under `static` ) with these.

**Comment by dsanson** [comment]
Success! Stack is still churning away building ghcjs stuff, so I followed your advice and replaced the ghcjs folder with your files. Then rebuilt Carnap-Server (`stack build`), and ran yesod per your instructions, and it works!

**Comment by dsanson** [comment]
Also needed to create the `../dataroot` and `../Carnap-Book/cache` folders.

**Comment by gleachkr** [comment]
We're now building everything reliably on GHCJS 8.6, and I've filed the relevant trac tickets, so I'm going to go ahead and close this issue.
