### ISSUE TITLE
Timeout on propositional equivalence check

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#40]
Equivalence checker does not manage to check formula with just 3 atoms.

See:

https://carnap.io/shared/rzach@ucalgary.ca/timeout.md

and click return.

**Comment by gleachkr** [comment]
Oy. The valuations that you use to check for truth table equivalence are produced by taking subsequences of the sequence of atoms occuring in the formula, and letting truth in the valuation correspond to membership in the subsequence. I forgot to deduplicate the sequence of atoms occuring in the formula. So, in your example, rather than checking 8 rows, it was checking (I think) 16777216 rows. I've fixed it locally and am currently deploying the fix.

**Comment by gleachkr** [comment]
OK, deployed. Should now behave a bit more reasonably with large numbers of atom occurances. Closed by 071d6c6.

**Comment by rzach** [comment]
Thanks!
