### ISSUE TITLE
Expose sequent proof checker for OLP

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#57]
Expose proof checker and editor for Gentzen sequent systems: LJ and LK with OLP syntax and Gentzen's standard rules, that is:

- Axioms are A |- A (no side formulas)
- No Rep rule
- Add weakening, contraction, and exchange rules (but allow them to apply to any number of formulas)
- Name the rules \*R/L instead of R/L\*
- Treat &L and vR as a single rule
- Do not require shared contexts in ->L and Cut rule
- Place/require active formulas on the outside rather than the inside

**Comment by gleachkr** [comment]
This is getting a bit closer. Two questions:

1. Would a contraction that only takes two formulas be OK, or that takes < N for some small N? This would be a bit simpler.

2. Would the following be an acceptable variation on exchange? 

Γ,φ,Γ' ⊢ Δ ∴ φ,Γ,Γ' ⊢ Δ

(and the symmetical version, of course). Again, this would be a little bit simpler, not requiring special-casing for the proof checker.

It would also be possible to have a version that sends a formula down into the stack, although I think that would be less useful.

**Comment by rzach** [comment]
My guess is that most actual proofs won't have too many formulas to contract or exchange so contracting only two formulas would be ok.  I think the version of exchange you propose is a bit unintuitive.  I'd be happy with treating sequents as sets or multisets, so have implicit contraction and exchange, if that's easier, perhaps with a dummy structural rule?

**Comment by gleachkr** [comment]
That would be a smaller revison of the current LK-ish system.

If treating things as sets is OK, then what remains to be done is renaming the rules, changing the axiom rule to disallow side-formulas, and adding weakening. I might just make these changes in the default LK system, and then perhaps something with stricter structural rules (possibly with an exchange rule allowing arbitrary permutations) could be added later.

Question: Would this be more intuitive, for exchange?

φ,Γ,ψ,Γ' ⊢ Δ ∴ ψ,Γ,φ,Γ' ⊢ Δ

**Comment by rzach** [comment]
Sounds good. In that case we don't have to worry about exchange, right? 

I think for exchange the standard rule that allows you to exchange two neighboring formulas anywhere is the only one I've ever seen. Anything else will be confusing to use I think.

But, I think treating things as sets would be ok. Multisets would be better, so you can maybe add contraction-free logics at some point.  I'm happy as long as Carnap will accept any inference as correct that's correct in the standard system, and is otherwise more lenient (eg doesn't require active formulas to be on the outside, doesn't require contracted formulas to be next to each other, doesn't require side formulas to be given in the same order in both premises, etc.).

It would be good to have the same dummy rule have 4 names (C/X L/R) so I can enter and label inferences according to the official rules.

**Comment by gleachkr** [comment]
I like the idea of giving the dummy structrual rule several names, so that proofs can be labeled officially.

What we'll end up with is probably going to *slightly* more restrictive than treating the entire LHS or RHS as a set, in one way: it will still require the active formulas in the conclusions of inferences to be on the outside. Carnap needs some kind of hint as to which formulas it'll be looking inside of, so this is pretty hard to get around. But as far as I can see, we'll still be able to pack all the structural manipulations (except weakening) into the ordinary inferences in this system.

**Comment by rzach** [comment]
I like this even better, as long as a single XL or XR will allow you to put the active formulas in the right place.

**Comment by rzach** [comment]
Hey how close is this?

**Comment by gleachkr** [comment]
I think maybe one day of work. I could try to get it done tomorrow, if you're thinking about using it.

**Comment by rzach** [comment]
No rush at all.

**Comment by rzach** [comment]
But if it were to magically become available I might use it next week

**Comment by gleachkr** [comment]
> What we'll end up with is probably going to _slightly_ more restrictive than treating the entire LHS or RHS as a set, in one way: it will still require the active formulas in the conclusions of inferences to be on the outside. Carnap needs some kind of hint as to which formulas it'll be looking inside of, so this is pretty hard to get around. But as far as I can see, we'll still be able to pack all the structural manipulations (except weakening) into the ordinary inferences in this system.

Rats, I missed something here. In the cut rule, carnap needs the active formulas in the premises as hints, since there are no active formulas in the conclusion sequent. So either: 

1. active formulas in all rules need to be on the outside in the conclusion, *except* for cut, where they need to on the outside in the premises
2. active formulas in premises and conclusions need to be on the outside in all rules.

Preference?

**Comment by rzach** [comment]
Let's do 2, less confusing I think

**Comment by gleachkr** [comment]
Excellent. I'm glad that's the one you went for, because I just implemented it.

**Comment by gleachkr** [comment]
OK, now deployed! The documentation for sequent calculi has been updated accordingly. The main system doesn't use the OLP syntax, but there are system strings `.openLogicFOLK`, `.openLogicFOLJ`, `.openLogicPropLK`, and `openLogicPropLJ` that ought to expose the documented system, but with the YYC 2019 syntax. So the code block would be, for example:

    ```{.Sequent .openLogicPropLK}
    1.1 P->Q, Q->R :|-: P->R
    ```

**Comment by rzach** [comment]
You're a star!

**Comment by gleachkr** [comment]
Thanks! :)

Please let me know if there are any rough spots!

**Comment by rzach** [comment]
1. Is there a `.SequentPlayground`?
2. I see hints/error boxes pop up on the left of the derivation. Since everything is left-aligned, that is often cut off by the left edge of the viewport. I would always display it on the right -- you can make the window larger on the right but not on the left.
3. ND systems are called `openLogicNK` and `openLogicFOLNK`. So for uniformity maybe `openLogicLK` and `openLogicFOLK`?
4. ND has a `prepopulate` option, and doesn't show the endformula unless you put it in. `.Sequent` seems to automatically put the endsequent in.  I don' tthink making students type out the end-sequent is a pedagogically useful option, but do we want consistency?
5. In general, I wonder if for the more advanced systems it's all that necessary to distinguish propositional and first order systems?  (At least for mine, the syntax is a fragment, and you don't have an advantage in the FO system if you just want to prove a propositional formula/sequent, so there's no harm in using the FOL systems always.)
6. Did you change the original system? The documentation https://carnap.io/shared/gleachkr@gmail.com/carnap-sequent-calculus.pandoc now looks like it's documenting the OLP/OG Gentzen systems.
7. There's something wonky going on with the &L rules in the documentation.

**Comment by rzach** [comment]
8. I regularly get confused (not just here) between `.systemX` and `system="systemX"`. Sometimes the latter works (not for these systems, but it did/does for NK).
9. Can we get LJ right away?

**Comment by rzach** [comment]
10. There seem to be problems with some rules: In https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20LK.md exercises 8.6 and 8.9 should show as correct.

**Comment by gleachkr** [comment]
> * Is there a `.SequentPlayground`?

No, but there could and probably should be. Maybe another issue for this?

> * I see hints/error boxes pop up on the left of the derivation. Since everything is left-aligned, that is often cut off by the left edge of the viewport. I would always display it on the right -- you can make the window larger on the right but not on the left.

I think this has something to do with how popperjs (which handles the popups) is trying to respond to the width of the viewport---it's probably getting confused by the fairly elaborate positioning of the nodes in the tree. I don't see this on a fullscreen window, but I do on my phone and on a small browser window. Tracking issue opened here: https://github.com/gleachkr/ProofJS/issues/12

> * ND systems are called `openLogicNK` and `openLogicFOLNK`. So for uniformity maybe `openLogicLK` and `openLogicFOLK`?

Sounds good. I'll change this.

> * ND has a `prepopulate` option, and doesn't show the endformula unless you put it in. `.Sequent` seems to automatically put the endsequent in.  I don't think making students type out the end-sequent is a pedagogically useful option, but do we want consistency?

I lean towards automatically prepopulating with sequents, since it's so natural to do them "bottom up", but a little less natural to do ND this way. Maybe if a use case emerges down the line, add an option to switch off prepopulation?

> * In general, I wonder if for the more advanced systems it's all that necessary to distinguish propositional and first order systems?  (At least for mine, the syntax is a fragment, and you don't have an advantage in the FO system if you just want to prove a propositional formula/sequent, so there's no harm in using the FOL systems always.)

Probably not necessary. I like presenting the propositional calculus separately since it's easy to prove soundness and completeness, but if you'd like to streamline the OLP offerings, we could consolidate those into just the first-order systems (and maybe just call them openLogicNK and openLogicLK)

> * Did you change the original system? The documentatio https://carnap.io/shared/gleachkr@gmail.com/carnap-sequent-calculus.pandoc now looks like it's documenting the OLP/OG Gentzen systems.

I did! So, the standard Gentzen systems are now just syntactic variants on the OLP systems.

> * There's something wonky going on with the &L rules in the documentation.

Indeed there is. ~Will fix!~ Fixed.

> I regularly get confused (not just here) between .systemX and system="systemX". Sometimes the latter works (not for these systems, but it did/does for NK).

The general idea is that a class string like `.systemX` is supposed to be shorthand for explicitly setting one or more attributes, like `system="systemX"` or `options="..."`. With the LK systems, since there isn't much to customize, the two are interchangable. But it looks like there's something in the way the pandoc is getting processed that's thowing away the manual setting of `system=`. Will fix.

> Can we get LJ right away?

It should already be working, via something like

    ```{.Sequent .openLogicPropLK}
    1.1 P->Q, Q->R :|-: P->R
    ```

But if not, please let me know!

**Comment by gleachkr** [comment]
> 1. There seem to be problems with some rules: In https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20LK.md exercises 8.6 and 8.9 should show as correct.

Looks like a typo in the specification of the rules. Will fix ASAP.

**Comment by gleachkr** [comment]
OK, typos in the rules should now be fixed.

**Comment by rzach** [comment]
Confirmed. LJ is there, thanks. `prepopulate` as default for LK makes sense. Playground is its own issue.
Can close as far as I'm concerned; will file new issues for specific problems.  (Some of which may be ProofJS issues anyway.)
