### ISSUE TITLE
Should not accept ->I  

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#61]
Not sure what the issue is exactly but the last line in this proof:

https://carnap.io/shared/rzach@ucalgary.ca/issue61.md

should not check out, as the assumption of the subproof cited is not identical to the antecedent of the conditional.

In general, it seems odd that you'd have a proof in which every line checks (+) and the last line is the goal but the proof as a whole doesn't check (turns green).

**Comment by gleachkr** [comment]
Thanks for catching that. It looks like the TFL2019 systems are using a less strict form of conditional introduction than they should be. Will fix tomorrow.

The situation where you have every line checking out and the proof as a whole doesn't might make a little bit more intuitive sense in some of the Montague systems. Some of these let you make an assumption at any point in the proof, rather than at a specific point where it can be guaranteed to be discharged, as in a Fitch system. This makes it possible to have a proof in which every line is OK locally, but in which there's an undischarged assumption so that the proof as a whole doesn't check out.

**Comment by gleachkr** [comment]
Upon further reflection, it looks like there's a related bit of potentially confusing behavior in TFL that ought to be fixed. What's happening in the linked proof above is that some of the rules of indirect proof (like →I) don't check that the assumptions have the correct form when approving an inference. The bad assumptions then hang around undischarged, which is why you get a proof that's locally OK but globally bad. This is mostly easy to fix, by adding the assumptions to the set of lines that Carnap checks for having the right form before signing off on the inference. 

But in some cases, (I think the only case where this can arise is ↔I), it's not enough that the assumptions and conclusions all have the right form. You also want the assumptions to be *paired up* correctly with the conclusions in the various subproofs. This isn't automatic when you have more than one subproof. So, for example, the easy fix won't work, because it will still allow ↔I for A↔B via a subproof B∴B, and a subproof A∴A (althoguh the assumptions of these subproofs won't be discharged, so the proof globally won't check out).To to prevent the locally-good globally-bad situation from arising, a more involved check will be needed. I'll try to put that together tomorrow.

**Comment by gleachkr** [comment]
OK, I've put into place a new way of making sure that the assumptions in the TFL system proofs are of the right form. This should cover the issue you've noticed with conditional introduction, and the related potential issues with other rules. I think the way I'm doing things now is the way I should have done it in the first place. I'll work it into the other fitch systems, and this will hopefully let me reduce the number of different forms of inference rules that I need to consider.

**Comment by rzach** [comment]
Works for ZachTFL2019 but not yet for ZachTFL and also not for original forall x (updated test case file).

**Comment by gleachkr** [comment]
Yep, it needs to be put into place for each Fitch system. Working on that now. Thanks for the test file, that's very helpful.

**Comment by gleachkr** [comment]
This should now work for all the Calgary systems. ForallxSFL turns out to require generalizing the implementation of the check a little bit, because of the possibility in SFL of a subproof with more than one significant final line (for example, in the negation rules). I'll keep working on that one.

**Comment by gleachkr** [comment]
OK, with ef65aad3ba661ebcc772af44e53267a3c0442412, the relevant check has been generalized, and is now in place for the magnus forallx systems and the gamut fitch systems. So I think this can be closed
