### ISSUE TITLE
Show/Copy/Paste JSON options for .TreeDeduction 

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#67]
There should be an option for `.TreeDeduction` and `.TreePlayground` widgets to a) show the JSON of the tree, b) copy the JSON to the clipboard, and c) load a tree from JSON on the clipboard. Without something like that it'll be hard to help students: they might send in a screenshot of what they are doing but there won't be a way to load what they have into the proof editor.  

Of course, loading JSON from the clipboard into an assigned problem would let students copy other people's assignment. Perhaps that option could be shown only to instructors?

**Comment by gleachkr** [comment]
Just added a `displayJSON` option (settable with ~`settings="displayJSON"`~ `options="displayJSON"`) that creates a pane with an editable JSON display. This is probably good for some uses, but it it's going to be exposed to students rather than just as a tool for instructors creating exercises, it should probably have some way of toggling visibility. (`Ctrl-?`

I see your point about copying, but I'm not sure it's so much worse that students being able to copy other kinds of exercises - and students who want to cheat can always reconstruct a proof from a screenshot...

**Comment by rzach** [comment]
Great! I guess as long as there is an easy way for me to play with a proof I get from a student withou having to recreate it from a screenshot, I'd be happy.

**Comment by gleachkr** [comment]
OK, the `displayJSON` option now doesn't initially display the JSON pane, but only shows it when you press `Ctrl-?` in one of the input fields for the proof (you'll need the shift key too, on most keyboards, to get the "?" character). You can toggle it back off with the same keystroke.

**Comment by rzach** [comment]
Hm I don't seem to be able to get it to work. I added it to the last problem and the playground on https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20ND.md but Ctrl+? doesn't do anything.

**Comment by gleachkr** [comment]
Shoot, I'm sorry, typo on my part above. It should be `options="displayJSON"`.

**Comment by rzach** [comment]
That works, thanks.

**Comment by gleachkr** [comment]
I should add this to the docs, but after that, should this be closed?

**Comment by rzach** [comment]
Is there a "load proof from JSON on clipboard" function yet?

**Comment by gleachkr** [comment]
Editing the JSON in the panel updates the proof (as long as the JSON is well formed) so it should work to just paste into there.

**Comment by rzach** [comment]
Ah, that's great. Yes, that's it as far as I'm concerned.

**Comment by gleachkr** [comment]
OK, documentation updated! Going to call this one finished.
