### ISSUE TITLE
Syntax-only checking of translation exercises

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#73]
When assigning translation problems as exam questions, I'd rather not have to deal with almost correct solutions which are just missing a parenthesis. Is it possible either make the `exam` option on translation exercises not accept things that don't parse, or enable a check option that will say if a sentence is grammatical but offer no feedback beyond that?

**Comment by gleachkr** [comment]
OK, I've put something in. The idea is that there would be a new `syntaxcheck` option, which you can combine with the `exam` option to block the submission of ill-formed answers. This is independent of the `nocheck` option, so you can still enable or disable the confirmation that an answer is correct.

Does that sound OK?

**Comment by rzach** [comment]
That sounds great! However, for uniformity might it not be better do the same as the proof checker does (ie, a `feedback` option with keys `syntaxonly` and `none` keys)?

**Comment by gleachkr** [comment]
Yeah, the current way is not the best from a unformity perspective. I wonder about this:  in derivations, `feedback=syntaxonly` is currently separable from `exam`. Maybe we could use `feedback=syntaxonly` in a similar way for translations. 

Part of #14 was switching to from check-on-enter-key to an explicit "check" button. I wonder if `feedback` could control this button, so that `none` would mean no button (kinda like how `nocheck` behaves now), `syntaxonly` would check only the syntax, `testsonly` would check tests too (like CNF, for example), and no setting would give a button that tests syntax, semantics, and tests, and tells you what's going wrong. That way choice of feedback button could be combined with any policy on what types of submissions to allow.

What do you think?

**Comment by rzach** [comment]
That sounds great. It's going to be a bit confusing to have `testsonly` mean "only tests except if you give another option then those too". Maybe have a `feedback=` option with `none`, `all`, `tests`, `syntax` possibilities and `all` being the default.

**Comment by gleachkr** [comment]
OK, deployed! I'll leave this issue open until I can upate the documentation.
