### ISSUE TITLE
forall x: Calgary >F19 systems

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#8]
As of the Fall 2019 forall x: Calgary has changed the syntax of FOL to surround arguments to predicate symbols with parentheses (and commas between arguments). The content has also been rearranged so that some proof problems have to be completed using only the basic rules. So I'd appreciate having available:

- a system option for TFL and FOL translation exercises to match this syntax. So like  thomasBolducAndZachFOL but with F(x, y) instead of Fxy. In the future I'll probably want to be able to use the ⊥ falsity constant in symbolization and truth tables, so having that already in the syntax would be wonderful.

- proof parser options that a) use this syntax but b) only allow the basic rules, for TFL and FOL separately. The basic rules are all the standard intro & elim rules, X, R, and IP.

- For completeness, FOL proof parser with new syntax and all derived rules allowed.

- Please do not render the outermost parentheses of formulas, and allow [ ] in addition to ( ) for readability. (Enforce parenthesis rules otherwise though)

Perhaps for backwards compatibility it would be best to define new syntax and proof parsers rather than redefine the thomasBolducAndZach versions -- say "forallxCalgaryTFL" and variations thereof.

**Comment by gleachkr** [comment]
Perhaps `thomasBolducAndZach[TFL|FOL]2019`, for the new systems? That fits reasonably well with existing conventions, and leaves room in case there are more tweaks down the line.

**Comment by rzach** [comment]
Ok with me although it does get a bit long, esp if you ant to distinguish between thomasBolducAndZachTFL2019BasicRules and thomasBolducAndZachTFL2019DerivedRules

**Comment by gleachkr** [comment]
True. There's a similar situation with some other systems (e.g. Magnus). Would it be OK to do 
`thomasBolducAndZachTFL2019` for the basic system, and `thomasBolducAndZachTFLPlus2019` for the extended one?

**Comment by rzach** [comment]
I'm ok with that too. Thanks!

**Comment by rzach** [comment]
BTW I should have stated that earlier: the syntax also allows sentence letters as constituents of FOL sentences. (It did so before this most recent version of forallx YYC but I'm not sure if carnap's thomasBolducAndZachFOL system allows it.)

**Comment by gleachkr** [comment]
OK, I think this should now all be ready to go - just deployed the changes.

The new systems are: `thomasBolducAndZachTFL2019`, `thomasBolducAndZachFOL2019` and `thomasBolducAndZachFOLPlus2019`. For derivations, you can use `.ZachTFL2019`, `.ZachFOL2019`, and `.ZachFOLPlus2019` as shorthand for this system setting with the proof-renderer on.

The changes are:

1. Sentence letters are now allowed in the FOL systems (also added this retroactively to the 2018 edition of the rules)
2. Predication in the 2019 systems now looks like `P(a,b)` rather than `Pab`.
3. The new non-plus systems don't include any forallx derived rules.
4. The 2019 systems do not render outermost parentheses.

The new systems are also allowable options in translation and truth-table exercises. You should be able to use ⊥ in translations and truth tables, and both parentheses and square brackets in formulas.

I might not have gotten everything you had in mind for allowing both parentheses and square brackets. Did you want these to also appear in rendered formulas? The difficulty here is that the choice of delimiter symbols use to write a formula isn't remembered once the formula is parsed, so it can't easily be recovered. There is a next-best option, which is to just alternate parentheses and square brackets when renderering - would it help to set that up?

**Comment by rzach** [comment]
Cool, thanks so much. Rendering of brackets as parentheses is fine. I have three things that don't seem to quite work:

1. The systems should enforce parentheses use. I think it used to before this update. But it doesn't complain about e.g. `B v E -> C` in translations and parses `A v B & C` in the proof editor as (A v B) & C.
2. The book allows s-z as variables. Is that easy to implement?  (I assume it's hard to do it for v since that also plays the role of or?)
3. FOL translations accept !? in the syntax, but the equivalence test doesn't seem to work. Eg `Ex F(x)` is recognized as equivalent to `~Ax ~F(x)` but not to `Ax~F(x) -> !?` or to `~Ax (F(x) -> !?)`.

**Comment by gleachkr** [comment]
Sounds good. Using v as a variable while using sentence letters might create some parsing issues, you're right. For example `AvB(v)` might be (A∨B(v)), or ∀vB(v). So skipping v is an option. I could also drop v as a connective and require `\/` instead, if that's preferable.

Thanks for the catch of the issue with !? - looks like I missed a case in the "extract propositional form" phase of the equivalence test. Should be easy to fix.

Just looked at the latest forallx for parentheses conventions. Am I right in thinking that the connectives also ought not be left-associative individually, so that basically dropping outer parens is the only paren convention?

**Comment by rzach** [comment]
If it's easy to do, let's remove `v` as a way to enter \lor and include 'v' as a variable.
Incidentally, I kinda liked LPL's convention of `@` for \forall and `3` for \exists.
Would it be easy to accept `_|_` for \bottom?
Yes re: no left-associative (forall x:YYC has always insisted on all parentheses except outermost).

**Comment by gleachkr** [comment]
OK, sounds good. All doable.

**Comment by gleachkr** [comment]
OK, just deployed another set of changes to the Calgary systems:

1. `v` no longer parses as ∨
2. `s`-`z` are now parsed as variables.
3. `_|_` is now parsed as ⊥
4. `3` and `@` are now parsed as ∃,∀ respectively (in the 2019 systems)
5. Parentheses are no longer dropped for associativity

And ⊥ should now be handled properly by the first-order equivalence checker.

**Comment by rzach** [comment]
Thanks so much! All of this works except 2: w is not recognized as a variable (`Ew F(w)` is reported as ungrammatical). Although s-v are parsed as variables, the equivalency checker seems to deal only with x-z (For `Ex F(x)` I get a "not quite try again" message when I input `Ev F(v)` but it accepts `Ez F(z)` as logically equivalent). Should I report this as a separate issue?

**Comment by rzach** [comment]
I noticed also that `v` no longer counts as `\/` also in `.ZachFTL` (i.e., the old system). That's ok with me personally but other people may be using that system and so any problem sets they have already  that use `v` for `\/` (but `system="thomasBolducZachTFL`) now no longer work (and their students may be confused).

**Comment by rzach** [comment]
One last thing: there is no separate system `ZachTFLPlus2019` for TFL + derived rules. Since that's the same as the old system `ZachTFL` it's not really needed. We should just document it.

**Comment by rzach** [comment]
I've documented all of this in a revision of the forall x documentation: https://carnap.io/shared/rzach@ucalgary.ca/carnap-forallx.pandoc

**Comment by gleachkr** [comment]
Excellent, thank you! I'll go ahead and replace my documentation with your revision.

Thanks also for the careful testing of the new parser. Both issues should now be fixed (basically caused by typos and forgetting to remove parsing for constant symbols that overlap with the new variables).

I did a quick check, and it looks like there aren't any saved exercises right now for the Calgary systems other than the ones you've created. So I think dropping `v` as ∨ought to be OK.

**Comment by rzach** [comment]
Tested and works. So I think this can be closed then. Thanks so much!

**Comment by gleachkr** [comment]
:+1:
