### ISSUE TITLE
Problems when assigning partial credit for translation exercises

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#80]
I have some translation exercises with `options="exam"`  at
https://carnap.io/assignments/Calgary%20Phil%20279%20L01%20Winter%202020/279%20Mock%20Test%202.md
and reviewing answers to assign extra credit shows as:

![Screenshot from 2020-03-23 17-02-06](https://user-images.githubusercontent.com/3122348/77371188-5b884c80-6d28-11ea-9544-c8e888c6c030.png)

- [x] it doesn't show the answer (or maybe the answer is just empty)
- [x] the correct solution doesn't parse, although it does parse correctly on the actual assignment
- [ ] the partial credit that I can assign is any positive or negative integer; it should probably just be between 0 and the point value of the problem. Maybe decimals should be allowed?

**Comment by gleachkr** [comment]
Thanks! The translation case was inadvertantly locked to the Carnap book systems. That's now fixed, so this should show up correctly on your assignment review page.

About the third check-box: I added some input validation, so that partial credit must now be a non-negative integer. I'm a little hesitant to do more. It'd be some extra complexity, and I can imagine cases where instructors might want to give some extra credit for a really excellent solution (i.e. with qualitative problems). Decimals would be hard, since points are scored as integers in the database. For that case, a workaround might be to scale up the points in your course to your desired resolution.

**Comment by rzach** [comment]
Ok, thanks! I'll close this and open another issue with a few minor UI items I'm noticing now that I'm playing with the exam/partial credit function.
