### ISSUE TITLE
Translation with option="exam" not tested for equivalence

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#82]
In problem MT2.1j I had a student submit the answer
` Ax(P(x,r)->((D(x)/\B(x))\/(C(x)/\O(x))))`
to https://carnap.io/shared/rzach@ucalgary.ca/279%20Mock%20Test%202.md
which Carnap scored as incorrect. But it is logically equivalent to the provided translation and Carnap recognizes this when `option="exam"` is not present, eg on:
https://carnap.io/shared/rzach@ucalgary.ca/279%20Mock%20Test%202%20noexam.md

So I suspect `options="exam"` bypasses the equivalence check.

**Comment by gleachkr** [comment]
OK, I've managed to reproduce the issue. It looks to me like it's actually got to do with whitespace at the beginning of the problem rather than the equivalence checker. Some parsers automatically absorb this, but it looks like the parser used for checking exam submissions does not. I included a failsafe for this in the correctness check, but not in the grading for exams. I'll fix shortly.
