### ISSUE TITLE
Point value display and calculation

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#97]
- [x] The point value of an exercise should perhaps be displayed?
- [x] What happens if the point value of an exercise set changes?  I thought that student scores get recomputed every time they are loaded, so expected scores to go up the point value in the document is changed. But I just did that (mistakenly assigned wrong point value) and the scores stayed the same. Not sure if that is as designed or a bug?

**Comment by rzach** [comment]
The problem I'm facing now is that I changed the point value on an exercise on a test after I made it available; how best to make sure that students who already submitted the exercise get the right score?

**Comment by gleachkr** [comment]
The point value is saved when the problem is submitted. That's used for computing the points awarded, on the basis of whether the problem was on time and so on, but the actual point value isn't reset after submission.

About the problem you're describing - one option would be to allow for assigning bonus points (or more generally point modifications) for correct problems, in the review area, so that it would be possible to modify the scores that are out of line with the indended value. This would be a little bit tedious, but might not be so bad if you can search within the page for occurances of the unindended value.

Another option would be to allow resubmission, so that students could resubmit correct work after a point-value change, and use that to override the saved value.

I think both of these are in the pipeline - would either help with the problem you're handling right now?

**Comment by rzach** [comment]
Option 1 would help.  Another solution would be a fix for issue #85 -- if I had a way of downloading the per-problem scores for a single problem set I could easily fix it.

**Comment by gleachkr** [comment]
OK, sounds good. I'll get something in ASAP.

**Comment by gleachkr** [comment]
Option 1 is now implemented and currently deploying (it was the easier to get done quickly). There's one question that this raises, which is whether the form validation that requires extra credit to be non-negative ought to be relaxed, for this kind of use case?

**Comment by gleachkr** [comment]
The review will now end up pulling in a lot more scores from the database. If you notice any slowness, please let me know.

**Comment by rzach** [comment]
Cool. Is the `Partial Credit Points` added to the submission score or does it replace it?  (If the latter, then no negative scores are necessary. It may be better to just make the points you enter override the submission score and call it `Override points`?

**Comment by gleachkr** [comment]
It's added, so if you want to reduce a score you'd need a negative number.

The override would be a nice solution, but it might be hard to transition, since there are already a lot of extra credit scores in the DB. You could have both, but that's added complexity, cruft and so on...

**Comment by rzach** [comment]
Ah I see. Did you give extra credit every?  I would think the main use case is to give partial credit for problems that were autograded at 0 points. Perhaps all the extra credit points in the DB are all actually added to an original score of 0? If so, converting to replacing the score would be no problem.

**Comment by gleachkr** [comment]
Good point. Let me check.

**Comment by gleachkr** [comment]
So, I'm still unsure about this. Nothing in the database would prevent the transition, but here are some more downsides that worry me. 

- I'd still have to make nonlocal changes to how scores are computed. 
- The database field, plus the accessors for the field, end up with confusing names that don't really reflect their functions. 
- People used to the old behavior might end up misgrading.

I think the negative scores approach ends up being a little cleaner.
